ignore:
  - "**/.git/**"
  - "**/.gitignore"
  - "**/.editorconfig"
  - "**/.DS_Store"
include:
  - ["%dotfiles%", .editorconfig]
dotfile_include:
  - ["%dotfiles%", dotfiles.nu]
encrypt:
  - "**/*.p12"
