brew:
  - carapace
  - fish
  - starship
  - nushell
scoop:
  - name: carapace-bin
    bucket: extras
  - starship
  - nu
posix:
  path:
    - "%config%"
    - nushell
darwin:
  path:
    - "%application-support%"
    - nushell
win:
  path:
    - "%appdata%"
    - nushell
ignore:
  - "**/history.txt"
  - "**/plugin.msgpackz"
  - "**/vendor/**"
