brew:
  - git
  - jq
  - ripgrep
  - fd
  - fzf
  - zoxide
  - resvg
  - yazi
scoop:
  - git
  - jq
  - ripgrep
  - fd
  - fzf
  - zoxide
  - resvg
  - yazi
ubuntu:
  brew:
    - "%root%"
    - xclip
    - xsel
posix:
  path:
    - "%config%"
    - yazi
win:
  path:
    - "%appdata%"
    - yazi
    - config
dotfile_source:
  - ["%path%", config.nu]
