brew:
  - git
  - jq
  - ripgrep
  - rg
  - fd
  - fzf
  - zoxide
  - resvg
  - yazi
scoop:
  - git
  - jq
  - ripgrep
  - rg
  - fd
  - fzf
  - zoxide
  - resvg
  - yazi
posix:
  path:
    - "%config%"
    - yazi
ubuntu:
  brew:
    - "%root%"
    - xclip
    - xsel
win:
  path:
    - "%appdata%"
    - yazi
    - config
