brew:
  - lazygit
scoop:
  - name: lazygit
    bucket: extras
posix:
  path:
    - "%config%"
    - lazygit
darwin:
  path:
    - "%application-support%"
    - lazygit
win:
  path:
    - "%appdata%"
    - lazygit
ignore:
  - "**/state.yml"
dotfile_source:
  - ["%path%", config.nu]
