brew:
  - lazygit
scoop:
  - name: lazygit
    bucket: extras
posix:
  path:
    - "%config%"
    - lazygit
darwin:
  path:
    - "%application_support%"
    - lazygit
win:
  path:
    - "%appdata%"
    - lazygit
ignore:
  - "**/state.yml"
