brew:
  - git
  - fzf
  - ripgrep
  - fd
  - neovim
scoop:
  - git
  - fzf
  - ripgrep
  - fd
  - neovim
posix:
  path:
    - "%config%"
    - neovim
win:
  path:
    - "%local-appdata%"
    - neovim
