brew:
  - git
  - fzf
  - ripgrep
  - rg
  - fd
  - neovim
scoop:
  - git
  - fzf
  - ripgrep
  - rg
  - fd
  - neovim
posix:
  path:
    - "%config%"
    - nvim
ubuntu:
  brew:
    - "%root%"
    - xclip
    - xsel
win:
  path:
    - "%local-appdata%"
    - nvim
