brew:
  - git
  - fzf
  - ripgrep
  - fd
  - cmake
  - llvm
  - fnm
  - neovim
scoop:
  - git
  - fzf
  - ripgrep
  - fd
  - cmake
  - llvm
  - fnm
  - neovim
ubuntu:
  brew:
    - "%root%"
    - xclip
    - xsel
posix:
  path:
    - "%config%"
    - nvim
win:
  path:
    - "%local-appdata%"
    - nvim
dotfile_env_source:
  - ["%path%", neovim-env.nu]
